swandask: Fix missing `cookie_secret` argument
This error was caused in `bleeding edge` software stack when connecting to HTCondor cluster.
This argument is necessary for Tornado using it to sign cookies.
Current jupyter_server version: 2.14.2

Tracestack:
```
2025-07-03 15:39:49,532 - SwanDask - INFO - Running SwanDask on port 56825 with base url /user/rhenriqu/
[I 2025-07-03 15:39:50.659 ServerApp] 200 GET /user/rhenriqu/api/metrics/v1?1751549990614 (rhenriqu@127.0.0.1) 5.28ms
[I 2025-07-03 15:39:51.076 ServerApp] 200 GET /user/rhenriqu/api/metrics/v1?1751549991014 (rhenriqu@127.0.0.1) 5.23ms
[I 2025-07-03 15:39:51.135 ServerApp] 200 GET /user/rhenriqu/ipyparallel/clusters?1751549991047 (rhenriqu@127.0.0.1) 49.25ms
/cvmfs/sft-nightlies.cern.ch/lcg/views/devswan/Thu/x86_64-el9-gcc13-opt/lib/python3.12/site-packages/jupyter_server/base/handlers.py:608: UserWarning: The Tornado web application does not have an 'identity_provider' defined in its settings. In future releases of jupyter_server, this will be a required key for all subclasses of `JupyterHandler`. For an example, see the jupyter_server source code for how to add an identity provider to the tornado settings: https://github.com/jupyter-server/jupyter_server/blob/v2.0.0/jupyter_server/serverapp.py#L242
  if type(self.identity_provider) is IdentityProvider and mod_obj.__name__ != __name__:
2025-07-03 15:39:51,439 - tornado.application - ERROR - Uncaught exception GET /user/rhenriqu/dask/clusters?1751549985698 (::1)
HTTPServerRequest(protocol='http', host='swan-k8s.cern.ch', method='GET', uri='/user/rhenriqu/dask/clusters?1751549985698', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/cvmfs/sft-nightlies.cern.ch/lcg/views/devswan/Thu/x86_64-el9-gcc13-opt/lib/python3.12/site-packages/tornado/web.py", line 1769, in _execute
    result = await result  # type: ignore
             ^^^^^^^^^^^^
  File "/cvmfs/sft-nightlies.cern.ch/lcg/views/devswan/Thu/x86_64-el9-gcc13-opt/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 751, in prepare
    await super().prepare()
  File "/cvmfs/sft-nightlies.cern.ch/lcg/views/devswan/Thu/x86_64-el9-gcc13-opt/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 623, in prepare
    _user = await _user
            ^^^^^^^^^^^
  File "/cvmfs/sft-nightlies.cern.ch/lcg/views/devswan/Thu/x86_64-el9-gcc13-opt/lib/python3.12/site-packages/jupyter_server/auth/identity.py", line 236, in _get_user
    _cookie_user = self.get_user_cookie(handler)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cvmfs/sft-nightlies.cern.ch/lcg/views/devswan/Thu/x86_64-el9-gcc13-opt/lib/python3.12/site-packages/jupyter_server/auth/identity.py", line 396, in get_user_cookie
    _user_cookie = handler.get_secure_cookie(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cvmfs/sft-nightlies.cern.ch/lcg/views/devswan/Thu/x86_64-el9-gcc13-opt/lib/python3.12/site-packages/tornado/web.py", line 840, in get_signed_cookie
    self.require_setting("cookie_secret", "secure cookies")
  File "/cvmfs/sft-nightlies.cern.ch/lcg/views/devswan/Thu/x86_64-el9-gcc13-opt/lib/python3.12/site-packages/tornado/web.py", line 1673, in require_setting
    raise Exception(
Exception: You must define the 'cookie_secret' setting in your application to use secure cookies
[E 2025-07-03 15:39:51.617 ServerApp] {
      "Cookie": "jupyterhub-user-rhenriqu=[secret]; _xsrf=[secret]; jupyterhub-session-id=[secret]",
      "Priority": "u=1, i",
      "Accept-Encoding": "gzip, deflate, br, zstd",
      "Referer": "https://swan-k8s.cern.ch/user/rhenriqu/lab?",
      "Sec-Fetch-Dest": "empty",
      "Sec-Fetch-Mode": "cors",
      "Sec-Fetch-Site": "same-origin",
      "Accept-Language": "pt-PT,pt;q=0.8",
      "Sec-Gpc": "1",
      "Accept": "*/*",
      "X-Xsrftoken": "MnwxOjB8MTA6MTc1MTU0OTk4M3w1Ol94c3JmfDEzMjpZMlF6Tm1Vek4yTmhOR1l6TkRCa1pHRXdOekF5WXpNd016SXdabU14TlRJNlpEZGtNekV4TVRVM1l6ZzJNRE5qTWpKbVl6YzBNVEkxT1RFMVpqSTJabUUzWWpGaE16WXdaamMzTURSa00yVXpObVZoTkdRek5EQmtaV05qTVRZMk1nPT18NDRmODUzMmU4ZmMwMjU4OGUxZjk5YjFmNmY3YTJkODVkYjM4Y2Q4NjUyNGJkOTQ2OGNjMGQ0M2Y5YTk0NWI0MA",
      "Sec-Ch-Ua-Mobile": "?0",
      "Content-Type": "application/json",
      "Sec-Ch-Ua": "\"Not)A;Brand\";v=\"8\", \"Chromium\";v=\"138\", \"Brave\";v=\"138\"",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36",
      "Authorization": "token [secret]",
      "Sec-Ch-Ua-Platform": "\"macOS\"",
      "X-Scheme": "https",
      "X-Forwarded-Scheme": "https",
      "X-Forwarded-Proto": "https,http",
      "X-Forwarded-Port": "443,80",
      "X-Forwarded-Host": "swan-k8s.cern.ch",
      "X-Forwarded-For": "127.0.0.1,::ffff:10.100.99.64",
      "X-Real-Ip": "127.0.0.1",
      "X-Request-Id": "2477035c476615d1e258da51bfb88381",
      "Host": "swan-k8s.cern.ch"
    }
```